### ISSUE TITLE
Unknown directive widgetTemplate

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.z3cform.datagridfield#94]
I ran the included buildout without issues but when I start the instance I get this error. This happens with both Python 3.7 and 2.7. I looked at the docs for the widgetTemplate directive and the ZCML looks correct...

```
$ instance fg
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/Startup/starter.py:202: DeprecationWarning: set_default_debug_mode is deprecated. Please import from ZServer.ZPublisher.Publish.
  ZPublisher.Publish.set_default_debug_mode(self.cfg.debug_mode)
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/Startup/starter.py:203: DeprecationWarning: set_default_authentication_realm is deprecated. Please import from ZServer.ZPublisher.Publish.
  ZPublisher.Publish.set_default_authentication_realm(
2019-12-16 20:24:40 INFO ZServer HTTP server started at Mon Dec 16 20:24:40 2019
        Hostname: 0.0.0.0
        Port: 8080
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/Products.CMFUid-3.0.1-py2.7.egg/Products/CMFUid/UniqueIdHandlerTool.py:24: DeprecationWarning: InitializeClass is deprecated. Please import from AccessControl.class_init.
  from App.class_init import InitializeClass
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/Products.CMFEditions-3.3.2-py2.7.egg/Products/CMFEditions/StandardModifiers.py:46: DeprecationWarning: ComponentLookupError is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ComponentLookupError
2019-12-16 20:24:43 WARNING Init Class Products.CMFFormController.ControllerPythonScript.ControllerPythonScript has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
2019-12-16 20:24:43 WARNING Init Class Products.CMFFormController.ControllerValidator.ControllerValidator has a security declaration for nonexistent method 'ZPythonScriptHTML_changePrefs'
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/Products.CMFPlacefulWorkflow-2.0.0-py2.7.egg/Products/CMFPlacefulWorkflow/permissions.py:5: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
2019-12-16 20:24:43 WARNING ZODB.FileStorage Ignoring index for /Users/kimnguyen/src/collective.z3cform.datagridfield/var/filestorage/Data.fs
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/plone.app.upgrade-2.0.27-py2.7.egg/plone/app/upgrade/__init__.py:167: DeprecationWarning: LockItem is deprecated. Please import from OFS.LockItem.
  from webdav.LockItem import LockItem
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/plone.subrequest-1.9.1-py2.7.egg/plone/subrequest/__init__.py:18: DeprecationWarning: zope.site.hooks has moved to zope.component.hooks. Import of zope.site.hooks will become unsupported in Version 5.0
  from zope.site.hooks import getSite
/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/z3c.caching-2.1-py2.7.egg/z3c/caching/interfaces.py:2: DeprecationWarning: IObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import IObjectEvent
Traceback (most recent call last):
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/parts/instance/bin/interpreter", line 284, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/Startup/run.py", line 64, in <module>
    run()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/Startup/run.py", line 25, in run
    starter.prepare()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/Startup/starter.py", line 84, in prepare
    self.startZope()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/Startup/starter.py", line 313, in startZope
    ZServer.Zope2.startup()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/ZServer-4.0.1-py2.7.egg/ZServer/Zope2/__init__.py", line 32, in startup
    _startup()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/Zope-4.1.1-py2.7.egg/Zope2/App/startup.py", line 143, in startup
    load_zcml()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/Zope-4.1.1-py2.7.egg/Zope2/App/startup.py", line 58, in load_zcml
    load_site()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/Zope-4.1.1-py2.7.egg/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 703, in end
    self.stack.pop().finish()
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 868, in finish
    actions = self.handler(context, **args)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 354, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 268, in startElementNS
    self._handle_exception(ex, info)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/xmlconfig.py", line 266, in startElementNS
    self.context.begin(name, data, info)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 700, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 1070, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 891, in contained
    factory = self.context.factory(self.context, name)
  File "/Users/kimnguyen/src/collective.z3cform.datagridfield/eggs/zope.configuration-4.3.1-py2.7.egg/zope/configuration/config.py", line 630, in factory
    raise ConfigurationError("Unknown directive", ns, n)
zope.configuration.exceptions.ConfigurationError: ('Unknown directive', u'http://namespaces.zope.org/z3c', u'widgetTemplate')
    File "/Users/kimnguyen/src/collective.z3cform.datagridfield/parts/instance/etc/site.zcml", line 15.2-15.55
    File "/Users/kimnguyen/src/collective.z3cform.datagridfield/parts/instance/etc/package-includes/002-collective.z3cform.datagridfield-configure.zcml", line 1.0-1.76
    File "/Users/kimnguyen/src/collective.z3cform.datagridfield/src/collective/z3cform/datagridfield/configure.zcml", line 49.2
```

**Comment by erral** [comment]
We are using version 1.5.1 in Plone 5.2 and python 3.7 without issues.

**Comment by agitator** [comment]
@tkimnguyen came across this error too... thought is was my weird project setup...
anyhow I managed to fix it for my case in  https://github.com/collective/collective.z3cform.datagridfield/tree/package-dep-includes
Try it out, feedback welcome ;-)

**Comment by petschki** [comment]
fix merged and released. I'll close this one
